use_frameworks!

platform :ios, '8.0'

target 'KPengUtils_Example' do
  pod 'KPengUtils', :path => '../'

  target 'KPengUtils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
